name: Publish Docker Image to development

on:
  push:
    branches:
    - develop

permissions:
  pull-requests: write

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:

    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }} # Checkout para a branch atual

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # Use a versão mais recente do .NET 7.0 disponível

    - name: Install dependencies
      run: dotnet restore  src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln

    - name: Build the project
      run: dotnet build --no-restore --configuration Release  src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal  src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln

    - uses: chill-viking/dotnet-sonar-scanner@v2
      name: Sast Scan and Publish
      with:
        sonar-project-key: 'PosTechFiap33_controle-pedidos-api-pedidos'
        sonar-org-key: 'postechfiap33'
        token: ${{ secrets.GITHUB_TOKEN }}
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        working-directory: './src/app/ControlePedido.Pedidos'
        checkout: false

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPONAME }}:dev .
      working-directory: src/app # Path to your Dockerfile

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPONAME }}:dev
