name: .NET Build and Test Workflow

on:
  push:
    branches:
    - feature**

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }} # Checkout the current branch

    # Set up .NET SDK
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # Using the latest .NET 8.0 version

    # Install dotnet-coverage tool
    - name: Install dotnet-coverage tool
      run: dotnet tool install --global dotnet-coverage

    # Install dependencies
    - name: Install dependencies
      run: dotnet restore src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln

    # Build the project
    - name: Build the project
      run: dotnet build --no-restore --configuration Release src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln

    # Run tests and collect code coverage in XML format
    - name: Run tests and collect code coverage
      run: dotnet test src/app/ControlePedido.Pedidos/ControlePedidos.Pedidos.sln --configuration Release --collect:"XPlat Code Coverage"

    - uses: chill-viking/dotnet-sonar-scanner@v2
      name: Scan and Publish
      with:
        sonar-project-key: 'PosTechFiap33_controle-pedidos-api-pedidos'
        sonar-org-key: 'postechfiap33'
        token: ${{ secrets.GITHUB_TOKEN }}
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        working-directory: './src/app/ControlePedido.Pedidos'
        checkout: true
